baseURL: "https://jason.re"
languageCode: "en-us"
title: "Thoughts, Links & Moods"
theme: "hemingway"
#publishDir: docs
summaryLength: 50
paginate: 6
canonifyURLs: false
footnoteReturnLinkContents: "↩"
plainIDAnchors: true
autolink: false
assetDir: "static"
# Date String Format: Mon Jan 2 15:04:05 MST 2006
#sectionPagesMenu: main
permalinks:
  posts: /post/:title
  status: /status/:2006:01:02:150405
  links: /:section/:2006:01:02:150405
  pictures: /:section/:title
taxonomies:
  tag: tags
  type: type
  language: lang

timeZone: Europe/Berlin
frontmatter:
  date:
    - "date"
    - "lastmod"
    - "publishDate"
    - ":filename"
  publishDate:
    - "publishDate"
    - "date"
  lastmod:
    - "lastmod"
    - ":fileModTime"
    - "publishDate"
    - "date"

markup:
  goldmark:
    renderer:
      hardWraps: true
# if you want markdown WYSIWYG line break
#blackfriday:
#  extensions:
#    - "hardLineBreak"

# main menu
menu:
  main:
  - identifier: home
    name: "Home"
    title: "Home"
    url: "/"
    weight: 1
  - identifier: posts
    name: "Posts"
    title: "Posts"
    url: "/posts/"
    weight: 2
  - identifier: status
    name: "Status"
    url: "/status/"
    title: "Status Posts"
    weight: 3

params:
  mainSections:
  - posts
  - status
  author:
    given_name: "Jason"
    family_name: "Friedrich"
    display_name: "Jason Friedrich"
    thumbnail: "https://www.gravatar.com/avatar/3c4b5f09f9e988618881f349516028ab"
    image: "https://www.gravatar.com/avatar/3c4b5f09f9e988618881f349516028ab?s=250&d=mm&r=x"
    short_bio: "Just another left-handed, binge-watching tech geek who enjoys drinking coffee, playing video games and writing on the Internet."
    bio: "My name is Jason Friedrich. I am just another left-handed, binge-watching, tech geek who enjoys drinking coffee, playing video games and writing on the Internet. I've got my head stuck in the clouds for a living."
    about: "This is my chalkboard where I make up my mind and utter my opinion. Here I gather my tech related documentation, write about my experiences and try new stuff. I am located in the Ruhrgebiet area and write in English and native German."
    website: "https://friedrich.uk"
    social:
      github: "https://github.com/jbfriedrich"
      twitter: "https://twitter.com/jbfriedrich"
      mastodon: "https://mastodon.social/@jbf"
  email: "blog@jason.re"
  copyright: © 2021 Jason Friedrich
  friendly_url: jason.re

mediaTypes:
  application/atom:
    suffixes:
      - 'xml'

outputFormats:
  atom:
    baseName: 'index'
    isPlainText: false
    mediaType: 'application/atom'

outputs:
  home:
    - HTML
    - Atom
  section:
    - HTML
    - Atom

disableKinds:
  - 'RSS'

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
    disableInlineCSS: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true
