baseURL: "https://jason.re"
languageCode: "en-us"
title: "Thoughts, Links & Moods"
theme: "hemingway"
#publishDir: docs
summaryLength: 50
paginate: 12
canonifyURLs: false
footnoteReturnLinkContents: "↩"
plainIDAnchors: true
autolink: false
assetDir: "static"
# Date String Format: Mon Jan 2 15:04:05 MST 2006
#sectionPagesMenu: main
permalinks:
  posts: /post/:slug
  status: /status/:2006:01:02:150405
  links: /:section/:2006:01:02:150405
  pictures: /:section/:title
taxonomies:
  tag: tags
  type: type
  language: lang

timeZone: Europe/Berlin
frontmatter:
  date:
    - "date"
    - "lastmod"
    - "publishDate"
    - ":filename"
  publishDate:
    - "publishDate"
    - "date"
  lastmod:
    - "lastmod"
    - ":fileModTime"
    - "publishDate"
    - "date"

markup:
  goldmark:
    parser:
      attribute:
        block: true
      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: true
      unsafe: true
# if you want markdown WYSIWYG line break
#blackfriday:
#  extensions:
#    - "hardLineBreak"

# main menu
menu:
  main:
  - identifier: home
    name: "Home"
    title: "Home"
    pageref: "/"
    weight: 1
  - identifier: allposts
    name: "Posts"
    title: "Posts"
    pageref: "/posts/"
    weight: 2
  - identifier: allmicros
    name: "Updates"
    title: "Updates"
    pageref: "/status/"
    weight: 3
  footer:
  - identifier: feeds
    name: "Feeds"
    title: "RSS Feeds"
    pageref: "/feeds/"
    weight: 1
  - identifier: taglist
    name: "Tags"
    title: "Tags"
    pageref: "/tags/"
    weight: 2
  - identifier: Website
    name: "Website"
    title: "Website"
    url: "https://friedrich.uk"
    weight: 3
  - identifier: mastodon
    name: "Mastodon"
    title: "Mastodon"
    url: https://click.ba.it/@jason
    weight: 4

params:
  mainSections:
  - posts
  - status
  author:
    given_name: "Jason"
    family_name: "Friedrich"
    display_name: "Jason Friedrich"
    website: "https://friedrich.uk"
    fediverse_handle: "@jason@click.ba.it"
  email: "blog@jason.re"
  copyright: © 2024 Jason Friedrich
  friendly_url: jason.re

mediaTypes:
  application/atom:
    suffixes:
      - 'xml'

outputFormats:
  atom:
    baseName: 'index'
    isPlainText: false
    mediaType: 'application/atom'

outputs:
  home:
    - HTML
    - Atom
  section:
    - HTML
    - Atom

disableKinds:
  - 'RSS'

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: false
  x:
    disable: false
    enableDNT: true
    simple: false
    disableInlineCSS: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

ignoreErrors: error-remote-getjson
