baseURL: "https://jason.re"
languageCode: "en-us"
title: "Thoughts, Links & Moods"
theme: "hemingway"
#publishDir: docs
summaryLength: 50
paginate: 12
canonifyURLs: false
footnoteReturnLinkContents: "↩"
plainIDAnchors: true
autolink: false
assetDir: "static"
# Date String Format: Mon Jan 2 15:04:05 MST 2006
#sectionPagesMenu: main
permalinks:
  posts: /post/:slug
  status: /status/:2006:01:02:150405
  links: /:section/:2006:01:02:150405
  pictures: /:section/:title
taxonomies:
  tag: tags
  type: type
  language: lang

timeZone: Europe/Berlin
frontmatter:
  date:
    - "date"
    - "lastmod"
    - "publishDate"
    - ":filename"
  publishDate:
    - "publishDate"
    - "date"
  lastmod:
    - "lastmod"
    - ":fileModTime"
    - "publishDate"
    - "date"

markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
# if you want markdown WYSIWYG line break
#blackfriday:
#  extensions:
#    - "hardLineBreak"

# main menu
menu:
  main:
  - identifier: home
    name: "Home"
    title: "Home"
    url: "/"
    weight: 1
    pre: '<i role="img" class="bi bi-house-fill"></i>'
  - identifier: about
    name: "About"
    title: "About"
    url: "/about/"
    weight: 2
    pre: '<i role="img" class="bi bi-person-fill"></i>'
  - identifier: feeds
    name: "Feeds"
    title: "RSS Feeds"
    url: "/feeds/"
    weight: 3
    pre: '<i role="img" class="bi bi-rss-fill"></i>'
  - identifier: mastodon
    name: "Mastodon"
    title: "Mastodon"
    url: https://click.ba.it/@jason
    weight: 4
    pre: '<i role="img" class="bi bi-mastodon"></i>'
params:
  mainSections:
  - posts
  - status
  author:
    given_name: "Jason"
    family_name: "Friedrich"
    display_name: "Jason Friedrich"
    thumbnail: "https://www.gravatar.com/avatar/3c4b5f09f9e988618881f349516028ab"
    image: "https://www.gravatar.com/avatar/3c4b5f09f9e988618881f349516028ab?s=250&d=mm&r=x"
    website: "https://friedrich.uk"
  email: "blog@jason.re"
  copyright: © 2024 Jason Friedrich
  friendly_url: jason.re

mediaTypes:
  application/atom:
    suffixes:
      - 'xml'

outputFormats:
  atom:
    baseName: 'index'
    isPlainText: false
    mediaType: 'application/atom'

outputs:
  home:
    - HTML
    - Atom
  section:
    - HTML
    - Atom

disableKinds:
  - 'RSS'

privacy:
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: false
  twitter:
    disable: false
    enableDNT: true
    simple: false
    disableInlineCSS: true
  vimeo:
    disable: false
    simple: false
  youtube:
    disable: false
    privacyEnhanced: true

ignoreErrors: error-remote-getjson
