#publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images

backend:
  name: github
  repo: jbfriedrich/jason.re
  branch: master # Branch to update (optional; defaults to master)

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "/{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "feature_image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Type", name: "type", widget: "select", options: ["post", "micro", "link"], default: "post"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "de"]}
  - name: "micro" # Used in routes, e.g., /admin/collections/blog
    label: "Status" # Used in the UI
    folder: "/content/micros" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "/{{year}}/{{month}}/{{day}}/{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Type", name: "type", widget: "select", options: ["post", "micro", "link"], default: "micro"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "de"]}
  - name: "link" # Used in routes, e.g., /admin/collections/blog
    label: "Link" # Used in the UI
    folder: "/content/links" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    preview_path: "/links/{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Link Comment", name: "link_comment", widget: "markdown"}
      - {label: "Link URL", name: "link_url", widget: "string"}
      - {label: "Link Title", name: "link_title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Type", name: "type", widget: "select", options: ["post", "micro", "link"], default: "micro"}
      - {label: "Language", name: "language", widget: "select", options: ["en", "de"]}
